services:
  app:
    build:
      context: .
      target: builder
    command: sh -c -f "npm run start"
    restart: unless-stopped
    env_file: ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "50m" 
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
    - ./:/app
    ports:
      - "3000:3000"